-- MySQL Script generated by MySQL Workbench
-- Wed Dec 12 15:50:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema licenses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema licenses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS licenses DEFAULT CHARACTER SET utf8 ;
USE licenses ;

-- -----------------------------------------------------
-- Table licenses.lizenzen
-- -----------------------------------------------------
DROP TABLE IF EXISTS licenses.lizenzen ;

CREATE TABLE IF NOT EXISTS licenses.lizenzen (
  idlizenzen INT NOT NULL AUTO_INCREMENT,
  firma INT NOT NULL,
  produkt INT NOT NULL,
  anzahl INT NULL,
  ablaufdatum DATE NULL,
  PRIMARY KEY (idlizenzen),
  CONSTRAINT fk_lizenzen_firmen
    FOREIGN KEY (firma)
    REFERENCES licenses.firmen (idfirmen)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_lizenzen_produkte
    FOREIGN KEY (produkt)
    REFERENCES licenses.produkte (idprodukte)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table licenses.produkte
-- -----------------------------------------------------
DROP TABLE IF EXISTS licenses.produkte ;

CREATE TABLE IF NOT EXISTS licenses.produkte (
  idprodukte INT NOT NULL AUTO_INCREMENT,
  firma INT NOT NULL,
  produktname VARCHAR(30) NULL,
  stueckpreis FLOAT NULL,
  PRIMARY KEY (idprodukte),
  CONSTRAINT fk_produkte_firmen
    FOREIGN KEY (firma)
    REFERENCES licenses.firmen (idfirmen)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table licenses.firmen
-- -----------------------------------------------------
DROP TABLE IF EXISTS licenses.firmen ;

CREATE TABLE IF NOT EXISTS licenses.firmen (
  idfirmen INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NULL,
  ansvname VARCHAR(45) NULL,
  ansnname VARCHAR(45) NULL,
  anstel VARCHAR(45) NULL,
  ansemail VARCHAR(45) NULL,
  PRIMARY KEY (idfirmen))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table mydb.users
-- -----------------------------------------------------
DROP TABLE IF EXISTS licenses.users ;

/*CREATE TABLE IF NOT EXISTS licenses.users (
  idusers INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NULL,
  password VARCHAR(45) NULL,
  createdon DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (idusers))
ENGINE = InnoDB;*/

CREATE TABLE IF NOT EXISTS licenses.users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
  ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--Create Admin Account, username= admin, password= admin123
insert into users (id, username, password, created_at) values ('','admin','$2y$10$6Gw/cOHElnyLQUrIvqWd5..RPJ1DGW/puWx8qG1Jly8uTJpudKj7K','');

--Inserts Companies
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Microsoft','Bill','Gates','01234','email');
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Altium','Max','Mustermann','5678','email@altium.com');
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Musterfirma','Martina','Musterfrau','0123456789','email@muster.com');
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Amazon','Jeff','Bezos','391729381','jeff@bezos.com');
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Tesla','Elon','Musk','1231729381','elon@musk.com');
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Acer','Jason','Chen','0660552324','jason.chen@acer.com');
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Dell','Michael','Dell','066028192','michael@dell.com');
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Apple','Tim','Cook','0669352324','tim.cook@apple.com');
  insert into firmen (name, ansvname, ansnname, anstel,ansemail) values ('Dassault','Bernard','Charles','06645540050624','Bernard.Charles@dassault.com');
  

--Inserts Products
  insert into produkte (firma, produktname, stueckpreis) values (1,'Office365',99);
  insert into produkte (firma, produktname, stueckpreis) values (2,'Altium Designer',149);
  insert into produkte (firma, produktname, stueckpreis) values (3,'MathCAD',25);
  insert into produkte (firma, produktname, stueckpreis) values (1,'MSWord',10);
  insert into produkte (firma, produktname, stueckpreis) values (4,'Prime',50);
  insert into produkte (firma, produktname, stueckpreis) values (5,'Roadster',120000);
  insert into produkte (firma, produktname, stueckpreis) values (6,'Aspire F17',400);
  insert into produkte (firma, produktname, stueckpreis) values (7,'Inspirion',500);
  insert into produkte (firma, produktname, stueckpreis) values (8,'iMac',66666);
  insert into produkte (firma, produktname, stueckpreis) values (9,'SolidWorks',89);
  insert into produkte (firma, produktname, stueckpreis) values (9,'Model S',100000);
  insert into produkte (firma, produktname, stueckpreis) values (9,'Model X',120000);
  insert into produkte (firma, produktname, stueckpreis) values (9,'Model 3',45000);
  insert into produkte (firma, produktname, stueckpreis) values (9,'Semi',220000);
  insert into produkte (firma, produktname, stueckpreis) values (9,'Macbook',1230);


--Inserts Licenses for specific products
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (1,1,50,'2020-05-05');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (2,2,1400,'2022-10-04');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (3,3,1200,'2019-04-10');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (1,4,12200,'2031-04-10');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (4,5,500,'2023-03-20');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (5,6,1,'2030-12-14');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (5,11,1,'2019-04-19');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (5,12,1,'2019-04-19');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (5,13,2,'2019-04-19');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (5,14,1,'2019-04-19');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (6,7,6,'2023-11-20');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (7,8,3,'2028-07-30');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (8,9,1,'2029-04-19');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (8,15,2,'2019-04-19');
  insert into lizenzen (firma, produkt, anzahl, ablaufdatum) values (9,10,600,'2019-04-19');


--Select for testing the Database
select l.idlizenzen as Id, f.name as Firma, p.produktname as Produkt, l.anzahl as Anzahl, l.ablaufdatum as Ablaufdatum from lizenzen l, firmen f, produkte p where l.firma=f.idfirmen AND l.produkt=p.idprodukte;
